### PR TITLE
Pass missing required argument to connectSinksAndSources

### LINKED ISSUE #110: Taint analysis no longer works
It used to be possible to enable taint analysis by using `<?php // --taint-analysis`. This appears to be broken now, as the following exception is thrown, even for an empty snippet:

> Internal Psalm error on line 207 - /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/TaintFlowGraph.php: Too few arguments to function Psalm\Internal\Codebase\TaintFlowGraph::connectSinksAndSources(), 0 passed in /src/OnlineChecker.php on line 115 and exactly 1 expected

### PR DESCRIPTION
**Pull request by Daimona**
Needed to unbreak taint analysis, broken since https://github.com/vimeo/psalm/commit/babe8b2b7ec6de4f60e589fe3afd6120c9c8cdc8.

Fixes #110

### CODE REVIEW

**Review by muglug — APPROVED** [review]

**Comment by muglug** [comment]
Thanks!
